// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.chenj.protobuf;

public final class RPCDateServiceApi {
  private RPCDateServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenj_protobuf_RPCDateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenj_protobuf_RPCDateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenj_protobuf_RPCDateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenj_protobuf_RPCDateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\022com.chenj.protobuf\"\"" +
      "\n\016RPCDateRequest\022\020\n\010userName\030\001 \001(\t\"%\n\017RP" +
      "CDateResponse\022\022\n\nserverDate\030\001 \001(\t2\302\001\n\016RP" +
      "CDateService\022T\n\007getDate\022\".com.chenj.prot" +
      "obuf.RPCDateRequest\032#.com.chenj.protobuf" +
      ".RPCDateResponse\"\000\022Z\n\tListDates\022\".com.ch" +
      "enj.protobuf.RPCDateRequest\032#.com.chenj." +
      "protobuf.RPCDateResponse\"\000(\0010\001B)\n\022com.ch" +
      "enj.protobufB\021RPCDateServiceApiP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chenj_protobuf_RPCDateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chenj_protobuf_RPCDateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenj_protobuf_RPCDateRequest_descriptor,
        new String[] { "UserName", });
    internal_static_com_chenj_protobuf_RPCDateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chenj_protobuf_RPCDateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenj_protobuf_RPCDateResponse_descriptor,
        new String[] { "ServerDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
